version: "3.8"

networks:
  monitoring:

services:

  grafana:
    image: grafana/grafana:9.1.6
    ports:
      - "3000:3000"
    environment:
      GF_AUTH_ANONYMOUS_ENABLED: "true"
      GF_AUTH_DISABLE_LOGIN_FORM: "true"
      GF_AUTH_ANONYMOUS_ORG_ROLE: "Admin"
    volumes:
      - ./config/datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yml
      - grafana:/var/lib/grafana
    networks:
      - monitoring
    mem_limit: 300M
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "1"


  web-app:
    image: e2xen/devops-pythonapp:latest
    volumes:
      - ./logs/:/code/log/
    ports:
      - "80:80"

  promtail:
    image: grafana/promtail:2.6.1
    volumes:
      - ./logs/:/var/log/
      - ./config:/etc/promtail/
    ports:
      - "9080:9080"
    command: -config.file=/etc/promtail/promtail.yaml
    networks:
      - monitoring
    mem_limit: 300M
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "1"

  loki:
    image: grafana/loki:2.6.1
    ports:
      - "3100"
      - "7946"

    command: "-config.file=/etc/loki/local-config.yaml"
    networks:
      - monitoring
    mem_limit: 300M
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "1"

  prometheus:
    image: prom/prometheus:v2.27.0
    ports:
      - "9090:9090"
    volumes:
      - ./config/prometheus.yaml:/etc/prometheus/prometheus.yml
      - prometheus:/prometheus
    command:
      [
        '--log.level=debug',
        '--config.file=/etc/prometheus/prometheus.yml',
        '--query.lookback-delta=30s'
      ]
    networks:
      - monitoring
    mem_limit: 300M
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "1"

volumes:
  grafana:
  prometheus: